### ISSUE TITLE
Best way to add in two factor support?

### ISSUE THREAD

**Issue by dfalling** [AppDoctorIo/accesspass#23]
I'm hoping to eventually add in two factor authentication- likely WebAuthN.  Any thoughts on where that would best fit into the current system?  Cheers!

**Comment by jpiepkow** [comment]
2 factor authentication for (username,password) -> second form of auth is not to far off. I just need to add a flag to allow additional passed in params to the changeset.
 If thats the case then you could do the following for example:

1. allow for additional params like enable_two_factor and phone_number)
2. override insert_override to insert the twofactor information in a separate table with a transaction on the user insert so that they are rolled back together on failure.
3. override after_login to send a text to the linked phone number.
4.override login_return to instead of returning the tokens return something like %{additional_auth: "phone"}
5. build your own route to handle that additional_auth code and then use AccessPass.login directly to get tokens(maybe AccessPass actually needs a new method that does not do login check or anything and just passes back tokens for passed in information).

Or something along these lines. 

As for WebAuthN I think it would require a bit more change because password is not required.

The idea though is not to enable two-factor auth out the box but eventually get documentation good enough so you can just go to a guide section that walks you through adding different types of two factor auth. Right now the docs are kind of soso because some of the things you can do are complex and maybe to longwinded to end up in docs like team based auth(https://medium.com/@jpiepkow/team-based-login-with-accesspass-be236d4bd7dd). This is something I hope to revisit in the future.

**Comment by dfalling** [comment]
Awesome, thanks for the detailed writeup and blog post!  Good to know there's a path forward when I work on this.
