### ISSUE TITLE
Suggestion for persisting sessions?

### ISSUE THREAD

**Issue by dfalling** [AppDoctorIo/accesspass#42]
Because sessions are stored in a genserver, they're reset on app deploys.  Do you have any suggestions for preventing this reset?  The solutions I've tracked down seem to all require changes with starting the server so I can't change that in my app.

**Comment by jpiepkow** [comment]
I am on vacation currently but will be sure to provide you with some suggestions when I get back in 5 day!

**Comment by jpiepkow** [comment]
Sorry that took so long. Currently the package does not worry about persistent auth because we at AppDoctor use hot updating. If that is an option I suggest trying it out. For us it has been amazing because we do not have to drop socket connections or internal genserver state on code change. If not you may be able to add a pr to request the current cache from a member of the node group. Then on deploy request the cache before tearing down the old code. I have a couple more ideas but would need to know more about your deployment process. I should be able to respond much quicker now. Thanks!

**Comment by dfalling** [comment]
No worries for the delay, I've been swamped with other tickets.  I'm using Distillery currently, so hot updating is definitely an option.  I hadn't thought the genserver would survive that, so that's great news.  I'll dig into that approach- thanks!

**Comment by jpiepkow** [comment]
If you are changing the genserver state it can get a little complicated but if the state is "set in stone" and your updating non persistent related things then hot deploy is relatively easy depending on your deployment pipeline!

**Comment by dfalling** [comment]
Awesome, good to know.  So if I make changes to the access pass meta I should probably bounce the gen server to start fresh.

**Comment by jpiepkow** [comment]
Thats correct!
